version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      ruby-deps:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      node-deps:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"
